namespace Accountant.Enums;

public enum HousingZone : ushort
{
    Mist                  = 339,
    LavenderBeds          = 340,
    Goblet                = 341,
    Shirogane             = 641,
    Firmament             = ushort.MaxValue,
    ChambersMist          = 384,
    ChambersLavenderBeds  = 385,
    ChambersGoblet        = 386,
    ChambersShirogane     = 652,
    ChambersFirmament     = ushort.MaxValue - 1,
    ApartmentMist         = 608,
    ApartmentLavenderBeds = 609,
    ApartmentGoblet       = 610,
    ApartmentShirogane    = 655,
    ApartmentFirmament    = ushort.MaxValue - 2,
    CottageMist           = 282,
    CottageLavenderBeds   = 342,
    CottageGoblet         = 345,
    CottageShirogane      = 649,
    CottageFirmament      = ushort.MaxValue - 3,
    HouseMist             = 283,
    HouseLavenderBeds     = 343,
    HouseGoblet           = 346,
    HouseShirogane        = 650,
    HouseFirmament        = ushort.MaxValue - 4,
    MansionMist           = 284,
    MansionLavenderBeds   = 344,
    MansionGoblet         = 347,
    MansionShirogane      = 651,
    MansionFirmament      = ushort.MaxValue - 5,
}
