namespace Accountant.Enums;

public enum HousingZone : ushort
{
    Mist                  = 339,
    LavenderBeds          = 340,
    Goblet                = 341,
    Shirogane             = 641,
    Empyreum              = 979,
    ChambersMist          = 384,
    ChambersLavenderBeds  = 385,
    ChambersGoblet        = 386,
    ChambersShirogane     = 652,
    ChambersEmpyreum      = 983,
    ApartmentMist         = 608,
    ApartmentLavenderBeds = 609,
    ApartmentGoblet       = 610,
    ApartmentShirogane    = 655,
    ApartmentEmpyreum     = 999,
    CottageMist           = 282,
    CottageLavenderBeds   = 342,
    CottageGoblet         = 345,
    CottageShirogane      = 649,
    CottageEmpyreum       = 980,
    HouseMist             = 283,
    HouseLavenderBeds     = 343,
    HouseGoblet           = 346,
    HouseShirogane        = 650,
    HouseEmpyreum         = 981,
    MansionMist           = 284,
    MansionLavenderBeds   = 344,
    MansionGoblet         = 347,
    MansionShirogane      = 651,
    MansionEmpyreum       = 982,
}
