namespace Accountant.Enums;

public enum StringId
{
    Unknown,
    Mist,
    LavenderBeds,
    Goblet,
    Shirogane,
    Firmament,
    CropBed,
    CropPot,
    CropPatch,
    Cottage,
    House,
    Mansion,
    Apartment,
    Chambers,
    Airship,
    Submersible,
    Retainer,
    Retainers,
    Machines,
    Completed,
    Available,

    HarvestCrop,
    PlantCrop,
    RemoveCrop,
    TendCrop,
    FertilizeCrop,
    DisposeCrop,
    CropBeyondHope,
    CropDoingWell,
    CropBetterDays,
    CropReady,
    CropPrepareBed,
    PlantMatcher,
    PatchMatcher,
    SeedMatcher,
    WheelFilter,

    BuyMiniCactpotTicket,
    BuyJumboCactpotTicket,
    FilterJumboCactpotTicket,
}
